/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Modelo.Parqueos;
import Modelo.Usuarios;
import java.awt.Color;
import java.awt.Font;
import static java.lang.Integer.parseInt;
import java.util.List;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class Ajustes extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Ajustes()
    {
        //cambiarBorde();
        this.setTitle("Log in");
        initComponents();
        
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contrasenna = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(410, 700));
        setMinimumSize(new java.awt.Dimension(410, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        contrasenna.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        contrasenna.setForeground(new java.awt.Color(51, 51, 51));
        contrasenna.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        contrasenna.setToolTipText("Digite una nueva contraseña");
        contrasenna.setBorder(null);
        contrasenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasennaActionPerformed(evt);
            }
        });
        getContentPane().add(contrasenna);
        contrasenna.setBounds(40, 200, 272, 40);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajustes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 70, 170, 38);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clásico", "Oscuro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(40, 300, 140, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cambiar contraseña");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 160, 272, 31);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tamaño de fuente");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 360, 272, 31);

        jComboBox4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mediano", "Grande" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(40, 400, 140, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tema");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 260, 272, 31);

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 600, 130, 40);

        jComboBox5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "English" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(40, 490, 140, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Idioma");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 450, 272, 31);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel4.setText("Ready Parking");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 0, 270, 50);

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 40, 30);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(40, 610, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contrasennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasennaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_contrasennaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(!this.contrasenna.getText().equals(""))
        {
            UsuarioControlador us =  new UsuarioControlador();
            List<Usuarios> usuarios = us.todosLosUsuarios();
            
            for(Usuarios u: usuarios)
            {
                if(u.getId() == parseInt(this.Usuario.getText()))
                {
                    u.setPass(this.contrasenna.getText());
                    us.editar(u);
                }
            }
        }
        
        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.fondo(this.fondo.getIcon());
        eng.usuario(this.Usuario.getText());
        eng.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if(this.jComboBox4.getSelectedItem().toString().equals("Mediano") || this.jComboBox4.getSelectedItem().toString().equals("Medium"))
        {
            this.jLabel1.setFont( new Font( "Century Gothic" , Font.BOLD, 30 ));
            
            this.jLabel11.setFont( new Font( "Century Gothic" , Font.BOLD, 24 ));
            this.jLabel10.setFont( new Font( "Century Gothic" , Font.BOLD, 24 ));
            this.jLabel7.setFont( new Font( "Century Gothic" , Font.BOLD, 24 ));
            this.jLabel9.setFont( new Font( "Century Gothic" , Font.BOLD, 24 ));
        }
        if(this.jComboBox4.getSelectedItem().toString().equals("Grande") || this.jComboBox4.getSelectedItem().toString().equals("Big"))
        {
            this.jLabel1.setFont( new Font( "Century Gothic" , Font.BOLD, 35 ));
            this.jLabel1.setLocation(130, 70);
            
            this.jLabel11.setFont( new Font( "Century Gothic" , Font.BOLD, 27 ));
            this.jLabel10.setFont( new Font( "Century Gothic" , Font.BOLD, 27 ));
            this.jLabel7.setFont( new Font( "Century Gothic" , Font.BOLD, 27 ));
            this.jLabel9.setFont( new Font( "Century Gothic" , Font.BOLD, 27 ));
            
            
        }
        
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(this.jComboBox1.getSelectedItem().toString().equals("Clásico") || this.jComboBox1.getSelectedItem().toString().equals("Classic"))
        {
           fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); 
        }
        
        if(this.jComboBox1.getSelectedItem().toString().equals("Oscuro") || this.jComboBox1.getSelectedItem().toString().equals("Dark"))
        {
            fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado oscuro.png"))); 
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        if(this.jComboBox5.getSelectedItem().toString().equals("English"))
        {
            this.jLabel1.setText("Settings");
            this.jLabel7.setText("Theme");
            this.jLabel9.setText("Change Password");
            this.jLabel10.setText("Font Size");
            this.jLabel11.setText("Language");
            
            this.jButton3.setText("Save");     
            
            this.jComboBox1.removeItemAt(0);
            this.jComboBox1.addItem("Classic");
            this.jComboBox1.removeItemAt(0);
            this.jComboBox1.addItem("Dark");
            
            this.jComboBox4.removeItemAt(0);
            this.jComboBox4.addItem("Medium");
            this.jComboBox4.removeItemAt(0);
            this.jComboBox4.addItem("Big");
            
        }
        if(this.jComboBox5.getSelectedItem().toString().equals("Español"))
        {
            this.jLabel1.setText("Ajustes");
            this.jLabel7.setText("Ajustes");
            this.jLabel9.setText("Cambiar contraseña");
            this.jLabel10.setText("Tamaño de letra");
            this.jLabel11.setText("Idioma");
            
            this.jButton3.setText("Guardar");
            
            this.jComboBox1.removeItemAt(0);
            this.jComboBox1.addItem("Clásico");
            this.jComboBox1.removeItemAt(0);
            this.jComboBox1.addItem("Oscuro");
            
            this.jComboBox4.removeItemAt(0);
            this.jComboBox4.addItem("Mediano");
            this.jComboBox4.removeItemAt(0);
            this.jComboBox4.addItem("Grande");
        }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new Ajustes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usuario;
    private javax.swing.JTextField contrasenna;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables




}
