/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Controladores.vehiculoControlador;
import Modelo.Usuarios;
import Modelo.Vehiculos;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class AnnadirNuevoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public AnnadirNuevoVehiculo()
    {
        //cambiarBorde();
        this.setTitle("Log in");
        initComponents();
        
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
        
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Placa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Marca = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Modelo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Color = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Foto");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 120, 60, 31);

        Placa.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        Placa.setForeground(new java.awt.Color(51, 51, 51));
        Placa.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Placa.setBorder(null);
        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });
        getContentPane().add(Placa);
        Placa.setBounds(40, 350, 272, 40);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Añadir vehículo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 70, 240, 38);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Modelo");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 490, 272, 31);

        Tipo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedán", "Pick Up", "4x4", "Muscle", "" }));
        getContentPane().add(Tipo);
        Tipo.setBounds(40, 160, 110, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Marca");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 210, 100, 31);

        Marca.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RAM", "BMW", "Audi", "Toyota", "Nissan", "Peugeot" }));
        getContentPane().add(Marca);
        Marca.setBounds(40, 250, 110, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Placa");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 310, 272, 31);

        Modelo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018" }));
        getContentPane().add(Modelo);
        Modelo.setBounds(40, 530, 280, 40);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Color");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 400, 272, 31);

        Color.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Azul", "Rojo", "Gris", "Amarillo" }));
        getContentPane().add(Color);
        Color.setBounds(40, 440, 280, 40);

        Guardar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar);
        Guardar.setBounds(230, 600, 130, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 120, 70, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/PickUp.png"))); // NOI18N
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 160, 170, 130);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel2.setText("Ready Parking");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 0, 270, 50);

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 40, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(90, 110, 230, 10);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(30, 610, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PlacaActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        try
            {
                vehiculoControlador us =  new vehiculoControlador();
                Vehiculos usr = new Vehiculos(0,parseInt(this.Usuario.getText()),this.Tipo.getSelectedItem().toString(),this.Marca.getSelectedItem().toString(),
                        this.Placa.getText(),this.Color.getSelectedItem().toString(),this.Modelo.getSelectedItem().toString());
                us.crear(usr);
                JOptionPane.showMessageDialog(rootPane, "Vehículo añadido con éxito");
                this.dispose();
                menuPrincipal eng = new menuPrincipal();
                eng.usuario(this.Usuario.getText());
                eng.fondo(this.fondo.getIcon());
                eng.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error: " + e,
                    "Hey!", JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnnadirNuevoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnnadirNuevoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnnadirNuevoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnnadirNuevoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new AnnadirNuevoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> Marca;
    private javax.swing.JComboBox<String> Modelo;
    private javax.swing.JTextField Placa;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables




}
