/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.parqueoControlador;
import Modelo.Parqueos;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class comprarParqueo extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public comprarParqueo()
    {
        //cambiarBorde();
        this.setTitle("Comprar parqueo");
        initComponents();
        
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
        
        jButton2.setBackground(Color.WHITE);
        jButton2.setBorderPainted(false);
        
        
        
        
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void cargarParqueos()
    {
        parqueoControlador us =  new parqueoControlador();
        List<Parqueos> parqueos = us.todosLosParqueos();
        int controlador = 0;
        for(Parqueos u: parqueos)
        {
            if(u.getDisponible())
            {
                this.Parqueos.addItem("" + u.getZona() + "-" + u.getNumero());
            }
        }
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Parqueos = new javax.swing.JComboBox<>();
        parqueo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comprar Parqueo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 270, 38);

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 600, 130, 40);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel2.setText("Ready Parking");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 0, 270, 50);

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 40, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(70, 110, 260, 10);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(40, 600, 160, 25);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Parqueo");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 160, 110, 31);

        Parqueos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Parqueos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ParqueosItemStateChanged(evt);
            }
        });
        Parqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParqueosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ParqueosMouseExited(evt);
            }
        });
        Parqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParqueosActionPerformed(evt);
            }
        });
        getContentPane().add(Parqueos);
        Parqueos.setBounds(40, 200, 150, 40);

        parqueo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        parqueo.setForeground(new java.awt.Color(255, 255, 255));
        parqueo.setText("Zona 2 - Parqueo B066");
        parqueo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(parqueo);
        parqueo.setBounds(50, 280, 270, 31);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/parqueo1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 320, 180, 140);

        tipo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tipo.setForeground(new java.awt.Color(255, 255, 255));
        tipo.setText("- Tipo Amplio");
        tipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tipo);
        tipo.setBounds(230, 320, 160, 31);

        numero.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        numero.setForeground(new java.awt.Color(255, 255, 255));
        numero.setText("- Número 066");
        numero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(numero);
        numero.setBounds(230, 350, 160, 31);

        precio.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(255, 255, 255));
        precio.setText("- Sin techo");
        precio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(precio);
        precio.setBounds(230, 380, 160, 31);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int salir = JOptionPane.showConfirmDialog (null, "¿Comprar el parqueo?","Comprar",JOptionPane.YES_NO_OPTION);
        if(salir == 0)
        {
            
            String Parqueo = this.Parqueos.getSelectedItem().toString();
            String[] Spliteado = Parqueo.split("-");      
            System.out.print(" SplitComprar: "+Spliteado[0] + "-" + Spliteado[1]+"\n");
            
            parqueoControlador us =  new parqueoControlador();
            List<Parqueos> parqueos = us.todosLosParqueos();
            for(Parqueos u: parqueos)
            {
                 if(u.getZona().equals(Spliteado[0]) && u.getNumero().toString().equals(Spliteado[1]))
                {
                    u.setDisponible(false);
                    u.setIdDuenno(parseInt(this.Usuario.getText()));
                    us.editar(u);
                    break;
                }
                
                
            }            
            JOptionPane.showMessageDialog(rootPane, "Parqueo comprado con éxito");
            this.dispose();
            menuParqueos eng = new menuParqueos();
            eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
            eng.setVisible(true);   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        this.dispose();
        menuParqueos eng = new menuParqueos();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ParqueosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ParqueosItemStateChanged
        // TODO add your handling code here:

        String Parqueo = this.Parqueos.getSelectedItem().toString();
        String[] Spliteado = Parqueo.split("-");
        System.out.print(" Splits: "+Spliteado[0] + " - " + Spliteado[1]);

        parqueoControlador us =  new parqueoControlador();
        List<Parqueos> parqueos = us.todosLosParqueos();
        int controlador = 0;
        for(Parqueos u: parqueos)
        {
            System.out.print("\nParqueo: "+Spliteado[0]+Spliteado[1]+" Comparado con: " + u.getZona()+u.getNumero()+"\n");
            if(u.getZona().equals(Spliteado[0]) && u.getNumero().toString().equals(Spliteado[1]))
            {
                this.parqueo.setText("Zona " + u.getZona() + " Parqueo " + u.getZona()+u.getNumero());
                this.numero.setText("Número "+u.getNumero());
                this.precio.setText("Precio "+u.getPrecio());
                this.tipo.setText("Tipo "+u.getTipo());
                break;
            }
        }

    }//GEN-LAST:event_ParqueosItemStateChanged

    private void ParqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParqueosMouseClicked

    }//GEN-LAST:event_ParqueosMouseClicked

    private void ParqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParqueosActionPerformed
        /*
        if(this.Parqueos.getSelectedItem().toString().equals("B066"))
        {
            this.parqueo.setText("Zona B - Parqueo B066");
            //this.jLabel16.setText("- Sección B");
            this.numero.setText("- Número 066");
            this.precio.setText("- Sin Techo");
            this.tipo.setText("- Tipo Amplio");
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/parqueo1.png")));
        }
        if(this.Parqueos.getSelectedItem().toString().equals("A156"))
        {
            this.parqueo.setText("Zona A - Parqueo A156");
            //this.jLabel16.setText("- Sección A");
            this.numero.setText("- Número 156");
            this.precio.setText("- Con Techo");
            this.tipo.setText("- Tipo simple");
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/parqueo2.png")));
        }
        */
    }//GEN-LAST:event_ParqueosActionPerformed

    private void ParqueosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParqueosMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ParqueosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprarParqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new comprarParqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Parqueos;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel parqueo;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables




}
