/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Modelo.Usuarios;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login()
    {
        //cambiarBorde();
        this.setTitle("Log in");
        initComponents();
        
        //usuarioOCorreo.setText(" ");
        
        olvidoContrasenna.setOpaque(false);
        olvidoContrasenna.setContentAreaFilled(false);
        olvidoContrasenna.setBorderPainted(false);
        
        olvidoContrasenna.setVisible(false);
        jSeparator1.setVisible(false);
        
        crearUsuario.setOpaque(false);
        crearUsuario.setContentAreaFilled(false);
        crearUsuario.setBorderPainted(false);
        
        logIn.setBackground(Color.WHITE);
        logIn.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuarioOCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Contrasenna = new javax.swing.JPasswordField();
        olvidoContrasenna = new javax.swing.JButton();
        crearUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/perfil.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 120, 100, 110);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario o correo");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 260, 272, 31);

        usuarioOCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        usuarioOCorreo.setForeground(new java.awt.Color(51, 51, 51));
        usuarioOCorreo.setToolTipText("Digite el usuario o el correo");
        usuarioOCorreo.setBorder(null);
        usuarioOCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioOCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioOCorreo);
        usuarioOCorreo.setBounds(60, 300, 290, 40);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ready Parking");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 340, 60);

        logIn.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        logIn.setText("Iniciar Sesión");
        logIn.setToolTipText("Boton para iniciar sesión");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        getContentPane().add(logIn);
        logIn.setBounds(230, 610, 140, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 360, 272, 31);

        Contrasenna.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        Contrasenna.setToolTipText("Digite su contraseña");
        getContentPane().add(Contrasenna);
        Contrasenna.setBounds(60, 400, 290, 40);

        olvidoContrasenna.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        olvidoContrasenna.setForeground(new java.awt.Color(255, 255, 255));
        olvidoContrasenna.setText("¿Olvidó su contraseña?");
        olvidoContrasenna.setToolTipText("Botón por si olvidó su contraseña");
        olvidoContrasenna.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        olvidoContrasenna.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        olvidoContrasenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olvidoContrasennaActionPerformed(evt);
            }
        });
        getContentPane().add(olvidoContrasenna);
        olvidoContrasenna.setBounds(60, 520, 190, 17);

        crearUsuario.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuario.setText("Crear un usuario");
        crearUsuario.setToolTipText("Botón para crear un usuario");
        crearUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        crearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(crearUsuario);
        crearUsuario.setBounds(60, 480, 140, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(60, 540, 190, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(60, 500, 140, 10);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioOCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioOCorreoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usuarioOCorreoActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        
        UsuarioControlador us =  new UsuarioControlador();
        List<Usuarios> usuarios = us.todosLosUsuarios();
        boolean controlador = false;
        
        for(Usuarios u: usuarios)
        {
            if((this.usuarioOCorreo.getText().equals(u.getUsuario()) || this.usuarioOCorreo.getText().equals(u.getCorreo())) && this.Contrasenna.getText().equals(u.getPass()))
            {
                this.dispose();
                menuPrincipal eng = new menuPrincipal();
                eng.usuario(u.getId().toString());
                eng.setVisible(true);
                controlador = true;
            }
        }
        if(!controlador)
            JOptionPane.showMessageDialog(null, "Usuario o contraseña no validas",
                "Hey!", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_logInActionPerformed

    private void olvidoContrasennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olvidoContrasennaActionPerformed
        this.dispose();
        SignUp eng = new SignUp();
        eng.setVisible(true);
    }//GEN-LAST:event_olvidoContrasennaActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        this.dispose();
        SignUp eng = new SignUp();
        eng.setVisible(true);
    }//GEN-LAST:event_crearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contrasenna;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton logIn;
    private javax.swing.JButton olvidoContrasenna;
    private javax.swing.JTextField usuarioOCorreo;
    // End of variables declaration//GEN-END:variables




}
