/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.parqueoControlador;
import Controladores.vehiculoControlador;
import Modelo.Parqueos;
import Modelo.Vehiculos;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class misParqueos extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public misParqueos()
    {
        //cambiarBorde();
        this.setTitle("Mis parqueos");
        initComponents();
        
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        
        jButton1.setBackground(Color.WHITE);
        jButton1.setBorderPainted(false);
        
        limpiar();
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void cargarParqueos()
    {
        
        parqueoControlador us =  new parqueoControlador();
        List<Parqueos> parqueos = us.todosLosParqueos();
        int controlador = 0;
        System.out.print("\nQuiero ver mis parqueos con controlador "+ controlador+"\n");
        for(Parqueos u: parqueos)
        {
            if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
            {
                System.out.print("\nEncontró un parqueo\n");
                if(controlador==0)
                {
                    this.parqueo1.setText("Zona " + u.getZona()+" Parqueo " + u.getZona() + u.getNumero());
                    this.numero1.setText("Número "+u.getNumero());
                    this.precio1.setText("Precio "+ u.getPrecio());
                    this.tipo1.setText("Tipo "+u.getTipo());
                    this.foto1.setVisible(true);
                    controlador++;
                }
                else
                    if(controlador==1)
                    {
                        this.parqueo2.setText("Zona " + u.getZona()+" Parqueo " + u.getZona() + u.getNumero());
                        this.numero2.setText("Número "+u.getNumero());
                        this.precio2.setText("Precio "+ u.getPrecio());
                        this.tipo2.setText("Tipo "+u.getTipo());
                        this.foto2.setVisible(true);
                        controlador++;
                    }
            }
        }
    }
    
    public void limpiar()
    {
         System.out.print("\nVamos a limpiar mis parqueos\n");
        this.foto1.setVisible(false);
        this.numero1.setText("");
        this.parqueo1.setText("");
        this.tipo1.setText("");
        this.precio1.setText("");
        
        this.foto2.setVisible(false);
        this.numero2.setText("");
        this.parqueo2.setText("");
        this.tipo2.setText("");
        this.precio2.setText("");
        
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        parqueo1 = new javax.swing.JLabel();
        foto1 = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        numero1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        parqueo2 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        precio2 = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mis Parqueos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 80, 200, 38);

        parqueo1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        parqueo1.setForeground(new java.awt.Color(255, 255, 255));
        parqueo1.setText("Zona B - Parqueo B066");
        parqueo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(parqueo1);
        parqueo1.setBounds(30, 140, 270, 31);

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/parqueo1.png"))); // NOI18N
        foto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(foto1);
        foto1.setBounds(30, 180, 180, 140);

        tipo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tipo1.setForeground(new java.awt.Color(255, 255, 255));
        tipo1.setText("- Tipo Amplio");
        tipo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tipo1);
        tipo1.setBounds(220, 180, 160, 31);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setText("Ver en Mapa");
        jButton1.setToolTipText("Botón para ver el mapa del complejo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 600, 140, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 562, 320, 10);

        numero1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        numero1.setForeground(new java.awt.Color(255, 255, 255));
        numero1.setText("- Número 066");
        numero1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(numero1);
        numero1.setBounds(220, 210, 160, 31);

        precio1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        precio1.setForeground(new java.awt.Color(255, 255, 255));
        precio1.setText("- Techado");
        precio1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(precio1);
        precio1.setBounds(220, 240, 160, 31);

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/parqueo2.png"))); // NOI18N
        foto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(foto2);
        foto2.setBounds(30, 380, 180, 140);

        parqueo2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        parqueo2.setForeground(new java.awt.Color(255, 255, 255));
        parqueo2.setText("Zona A - Parqueo A156");
        parqueo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(parqueo2);
        parqueo2.setBounds(30, 340, 270, 31);

        numero2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        numero2.setForeground(new java.awt.Color(255, 255, 255));
        numero2.setText("- Número 156");
        numero2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(numero2);
        numero2.setBounds(220, 410, 160, 31);

        precio2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        precio2.setForeground(new java.awt.Color(255, 255, 255));
        precio2.setText("- Techado");
        precio2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(precio2);
        precio2.setBounds(220, 440, 160, 31);

        tipo2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tipo2.setForeground(new java.awt.Color(255, 255, 255));
        tipo2.setText("- Sencillo");
        tipo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(tipo2);
        tipo2.setBounds(220, 380, 160, 31);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(100, 120, 200, 2);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel2.setText("Ready Parking");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 0, 270, 50);

        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton3.setToolTipText("Boton para volver al menú de parqueos");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 10, 40, 30);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(30, 650, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        verMapa eng = new verMapa();
        eng.fondo(this.fondo.getIcon());
        eng.usuario(this.Usuario.getText());
        eng.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
        menuParqueos eng = new menuParqueos();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());    
        eng.setVisible(true);
        

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(misParqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(misParqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(misParqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(misParqueos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new misParqueos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero2;
    private javax.swing.JLabel parqueo1;
    private javax.swing.JLabel parqueo2;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precio2;
    private javax.swing.JLabel tipo1;
    private javax.swing.JLabel tipo2;
    // End of variables declaration//GEN-END:variables




}
