/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Controladores.vehiculoControlador;
import Modelo.Usuarios;
import Modelo.Vehiculos;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class misVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public misVehiculos()
    {
        //cambiarBorde();
        this.setTitle("Mis vehículos");
        initComponents();
        
        volver.setOpaque(false);
        volver.setContentAreaFilled(false);
        volver.setBorderPainted(false);
        
        AnnadirNuevo.setBackground(Color.WHITE);
        AnnadirNuevo.setBorderPainted(false);
        limpiar();
        //cargarVehiculos();
        
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void limpiar()
    {
        this.vehiculo1.setText("");
        this.color1.setText("");
        this.modelo1.setText("");
        this.placa1.setText("");
        
        this.vehiculo2.setText("");
        this.color2.setText("");
        this.modelo2.setText("");
        this.placa2.setText("");
        
        this.foto1.setVisible(false);
        this.foto2.setVisible(false);
    }
    
    public void cargarVehiculos()
    {
        vehiculoControlador us =  new vehiculoControlador();
        List<Vehiculos> vehiculos = us.todosLosVehiculos();
        int controlador = 0;
        for(Vehiculos u: vehiculos)
        {
            System.out.print("\n"+ u.getIdDuenno().toString() + " - "+ this.Usuario.getText()+"\n");
            if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
            {
                if(controlador==0)
                {
                    this.vehiculo1.setText(u.getTipo()+" "+u.getMarca());
                    this.color1.setText("- Color: "+u.getColor());
                    this.modelo1.setText("- Modelo: "+u.getModelo());
                    this.placa1.setText("- Placa: "+u.getPlaca());
                    this.foto1.setVisible(true);
                    controlador++;
                }
                else
                    if(controlador==1)
                    {
                        this.vehiculo2.setText(u.getTipo()+" "+u.getMarca());
                        this.color2.setText("- Color: "+u.getColor());
                        this.modelo2.setText("- Modelo: "+u.getModelo());
                        this.placa2.setText("- Placa: "+u.getPlaca());
                        this.foto2.setVisible(true);
                        controlador++;
                    }
            }
        }
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modelo1 = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        vehiculo1 = new javax.swing.JLabel();
        placa1 = new javax.swing.JLabel();
        color1 = new javax.swing.JLabel();
        foto1 = new javax.swing.JLabel();
        vehiculo2 = new javax.swing.JLabel();
        placa2 = new javax.swing.JLabel();
        color2 = new javax.swing.JLabel();
        modelo2 = new javax.swing.JLabel();
        AnnadirNuevo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mis vehículos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 70, 200, 38);

        modelo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        modelo1.setForeground(new java.awt.Color(255, 255, 255));
        modelo1.setText("- Modelo: 2015");
        modelo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(modelo1);
        modelo1.setBounds(190, 250, 160, 31);

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/bmw.png"))); // NOI18N
        foto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(foto2);
        foto2.setBounds(30, 370, 150, 110);

        vehiculo1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        vehiculo1.setForeground(new java.awt.Color(255, 255, 255));
        vehiculo1.setText("Pick Up RAM");
        vehiculo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vehiculo1);
        vehiculo1.setBounds(30, 140, 300, 31);

        placa1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        placa1.setForeground(new java.awt.Color(255, 255, 255));
        placa1.setText("- Placa: PKP-852");
        placa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(placa1);
        placa1.setBounds(190, 190, 160, 31);

        color1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        color1.setForeground(new java.awt.Color(255, 255, 255));
        color1.setText("- Color: Negro");
        color1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(color1);
        color1.setBounds(190, 220, 160, 31);

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/PickUp.png"))); // NOI18N
        foto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(foto1);
        foto1.setBounds(30, 180, 150, 110);

        vehiculo2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        vehiculo2.setForeground(new java.awt.Color(255, 255, 255));
        vehiculo2.setText("Sedán BMW");
        vehiculo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(vehiculo2);
        vehiculo2.setBounds(30, 330, 300, 31);

        placa2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        placa2.setForeground(new java.awt.Color(255, 255, 255));
        placa2.setText("- Placa: 275948");
        placa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(placa2);
        placa2.setBounds(190, 380, 160, 31);

        color2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        color2.setForeground(new java.awt.Color(255, 255, 255));
        color2.setText("- Color: blanco");
        color2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(color2);
        color2.setBounds(190, 410, 160, 31);

        modelo2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        modelo2.setForeground(new java.awt.Color(255, 255, 255));
        modelo2.setText("- Modelo: 1992");
        modelo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(modelo2);
        modelo2.setBounds(190, 440, 160, 31);

        AnnadirNuevo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        AnnadirNuevo.setText("Añadir nuevo");
        AnnadirNuevo.setToolTipText("Boton para añadir un nuevo vehículo");
        AnnadirNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnadirNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(AnnadirNuevo);
        AnnadirNuevo.setBounds(220, 600, 140, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 562, 320, 10);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel4.setText("Ready Parking");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 0, 270, 50);

        volver.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        volver.setToolTipText("Botón volver al menu");
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver);
        volver.setBounds(10, 10, 40, 30);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(100, 110, 200, 10);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(30, 610, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnnadirNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnadirNuevoActionPerformed
        this.dispose();
        AnnadirNuevoVehiculo eng = new AnnadirNuevoVehiculo();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);
    }//GEN-LAST:event_AnnadirNuevoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed

        
        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);
        
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(misVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(misVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(misVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(misVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new misVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnadirNuevo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel color1;
    private javax.swing.JLabel color2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel modelo1;
    private javax.swing.JLabel modelo2;
    private javax.swing.JLabel placa1;
    private javax.swing.JLabel placa2;
    private javax.swing.JLabel vehiculo1;
    private javax.swing.JLabel vehiculo2;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables




}
