/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Modelo.Usuarios;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public SignUp()
    {
        //cambiarBorde();
        this.setTitle("Registrarse");
        initComponents();
        Zona.setBackground(Color.WHITE);
        NumeroApartamento.setBackground(Color.WHITE);
        
        jButton1.setBackground(Color.WHITE);
        jButton1.setBorderPainted(false);
        
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        jLabel5.show(false);
        jLabel11.show(false);
        jLabel12.show(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Pass = new javax.swing.JPasswordField();
        Correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PassConfirmacion = new javax.swing.JPasswordField();
        NumeroApartamento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Zona = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de usuario");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 140, 272, 31);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("Debe llenar");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 270, 130, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("Debe llenar");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 180, 130, 40);

        Usuario.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        Usuario.setForeground(new java.awt.Color(51, 51, 51));
        Usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Usuario.setToolTipText("Digite un nombre de usuario");
        Usuario.setBorder(null);
        Usuario.setName("NombreUsuario"); // NOI18N
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(Usuario);
        Usuario.setBounds(30, 180, 340, 40);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel1.setText("Ready Parking");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 270, 50);

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 610, 130, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("No coincide");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 450, 130, 40);

        Pass.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        Pass.setToolTipText("Digite una contraseña");
        getContentPane().add(Pass);
        Pass.setBounds(30, 360, 340, 40);

        Correo.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        Correo.setForeground(new java.awt.Color(51, 51, 51));
        Correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Correo.setToolTipText("Digite su correo electrónico");
        Correo.setBorder(null);
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CorreoKeyPressed(evt);
            }
        });
        getContentPane().add(Correo);
        Correo.setBounds(30, 270, 340, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 230, 272, 31);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirmar contraseña");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 410, 272, 31);

        PassConfirmacion.setFont(new java.awt.Font("Century Gothic", 0, 17)); // NOI18N
        PassConfirmacion.setToolTipText("Repita su contraseña");
        PassConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassConfirmacionActionPerformed(evt);
            }
        });
        PassConfirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassConfirmacionKeyPressed(evt);
            }
        });
        getContentPane().add(PassConfirmacion);
        PassConfirmacion.setBounds(30, 450, 340, 40);

        NumeroApartamento.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        NumeroApartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        NumeroApartamento.setToolTipText("Seleccione el número de su apartamento");
        getContentPane().add(NumeroApartamento);
        NumeroApartamento.setBounds(210, 540, 160, 40);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apartamento");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 500, 272, 31);

        Zona.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Zona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zona", "A", "B", "C" }));
        Zona.setToolTipText("Seleccione la zona de su apartamento");
        Zona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZonaActionPerformed(evt);
            }
        });
        getContentPane().add(Zona);
        Zona.setBounds(30, 540, 160, 40);

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton2.setToolTipText("Volver al menú de inicio de sesión");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 40, 30);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 80, 210, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 120, 200, 2);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 320, 135, 31);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        System.out.print("jaja");
        
    }//GEN-LAST:event_UsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int validador = 0;
        jLabel5.show(false);
        jLabel11.show(false);
        if(!Pass.getText().equals(PassConfirmacion.getText()))
        {
            jLabel5.show(true); 
            validador +=1;
        }
        
        if(Usuario.getText().equals(""))
        {
            jLabel11.show(true); 
            validador +=1;
        }
        
        if(Correo.getText().equals(""))
        {
            jLabel12.show(true); 
            validador +=1;
        }
        
        if(this.NumeroApartamento.getSelectedItem().toString().equals("Número"))
        {
            JOptionPane.showMessageDialog(null, "Seleccione un número de apartamento",
                "Hey!", JOptionPane.ERROR_MESSAGE);
            validador +=1;
        }
        
        if(this.Zona.getSelectedItem().toString().equals("Zona"))
        {
            JOptionPane.showMessageDialog(null, "Seleccione una zona",
                "Hey!", JOptionPane.ERROR_MESSAGE);
            validador +=1;
        }
        
        if(validador == 0)
        {
            //Boton Conectar
            try
            {
                UsuarioControlador us =  new UsuarioControlador();
                Usuarios usr = new Usuarios(0,this.Usuario.getText(),this.Correo.getText(),this.Pass.getText(),Short.valueOf(this.NumeroApartamento.getSelectedItem().toString()),
                    this.Zona.getSelectedItem().toString());
                us.crear(usr);
                JOptionPane.showMessageDialog(null, "Usuario creado con éxito");
                this.dispose();
                Login eng = new Login();
                eng.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error: " + e,
                    "Hey!", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void ZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZonaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int salir = JOptionPane.showConfirmDialog (null, "¿Salir sin registrarse?","Salir",JOptionPane.YES_NO_OPTION);
        if(salir == 0)
        {
            this.dispose();
            Login eng = new Login();
            eng.setVisible(true);   
        }
        
                            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyPressed
        jLabel11.show(false);
    }//GEN-LAST:event_UsuarioKeyPressed

    private void CorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyPressed
       jLabel12.show(false);
    }//GEN-LAST:event_CorreoKeyPressed

    private void PassConfirmacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassConfirmacionKeyPressed
       jLabel5.show(false);
    }//GEN-LAST:event_PassConfirmacionKeyPressed

    private void PassConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassConfirmacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassConfirmacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Correo;
    private javax.swing.JComboBox<String> NumeroApartamento;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JPasswordField PassConfirmacion;
    private javax.swing.JTextField Usuario;
    private javax.swing.JComboBox<String> Zona;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables




}
