/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.MecanicoControlador;
import Controladores.ValletControlador;
import Controladores.vehiculoControlador;
import Modelo.Mecanicopedidos;
import Modelo.Valletpedidos;
import Modelo.Vehiculos;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class solicitarMecánico extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public solicitarMecánico()
    {
        //cambiarBorde();
        this.setTitle("Mecánico");
        initComponents();
        
        Dia.setBackground(Color.WHITE);
        Anno.setBackground(Color.WHITE);
        Vehiculos.setBackground(Color.WHITE);
        Mes.setBackground(Color.WHITE);
        
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void cargarVehiculos()
    {
        vehiculoControlador us =  new vehiculoControlador();
        List<Vehiculos> vehiculos = us.todosLosVehiculos();
        int controlador = 0;
        for(Vehiculos u: vehiculos)
        {
            if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
            {
                this.Vehiculos.addItem(u.getTipo()+"-"+u.getMarca());
            }
        }
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Anno = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        BotonSolicitar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Vehiculos = new javax.swing.JComboBox<>();
        Dia = new javax.swing.JComboBox<>();
        Mes = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(410, 700));
        setMinimumSize(new java.awt.Dimension(410, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitar Mecánico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 70, 270, 38);

        Anno.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Anno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024" }));
        Anno.setToolTipText("Combo para seleccionar el año");
        Anno.setEnabled(false);
        getContentPane().add(Anno);
        Anno.setBounds(280, 300, 90, 40);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Descripción del problema");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 360, 330, 31);

        BotonSolicitar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        BotonSolicitar.setText("Solicitar");
        BotonSolicitar.setToolTipText("Botón para solicitar el mecánico");
        BotonSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSolicitar);
        BotonSolicitar.setBounds(230, 600, 130, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehículo");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 150, 272, 31);

        Vehiculos.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Vehiculos.setToolTipText("Combo de despliegeu de vehiculos");
        getContentPane().add(Vehiculos);
        Vehiculos.setBounds(40, 200, 220, 40);

        Dia.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        Dia.setToolTipText("Combo para seleccionar el día");
        getContentPane().add(Dia);
        Dia.setBounds(40, 300, 70, 40);

        Mes.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        Mes.setToolTipText("Combo para seleccionar el mes");
        getContentPane().add(Mes);
        Mes.setBounds(120, 300, 150, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Fecha");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 260, 272, 31);

        Descripcion.setColumns(20);
        Descripcion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Descripcion.setRows(5);
        Descripcion.setToolTipText("Área para describir el problema del vehículo");
        jScrollPane1.setViewportView(Descripcion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 400, 330, 180);

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton9.setToolTipText("Botón para volver al menú principal");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 40, 30);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel4.setText("Ready Parking");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 0, 270, 50);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(60, 110, 270, 10);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(40, 600, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitarActionPerformed
        int salir = JOptionPane.showConfirmDialog (null, "¿Solicitar Mecánico?","Mecánico",JOptionPane.YES_NO_OPTION);
        if(salir == 0)
        {
            
            String Vehiculo = this.Vehiculos.getSelectedItem().toString();
            String[] Spliteado = Vehiculo.split("-");      
            System.out.print(" VehiculoSplit: "+Spliteado[0] + "-" + Spliteado[1]+"\n");
            
            vehiculoControlador us =  new vehiculoControlador();
            List<Vehiculos> vehiculos = us.todosLosVehiculos();
            int idVehiculo =0;
            for(Vehiculos u: vehiculos)
            {
                if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
                {
                   if(u.getTipo().equals(Spliteado[0]) && u.getMarca().equals(Spliteado[1]))
                       idVehiculo = u.getId();
                }
            }
            
            try
            {
                int mes = this.Mes.getSelectedIndex();
                String fechaEscogida = ""+this.Anno.getSelectedItem().toString()+"/" +String.valueOf(mes) + "/" + this.Dia.getSelectedItem().toString();   
                Date fecha = new SimpleDateFormat("yyyy/MM/dd").parse(fechaEscogida);
                
                MecanicoControlador us2 =  new MecanicoControlador();
                Mecanicopedidos usr = new Mecanicopedidos(0,parseInt(this.Usuario.getText()),idVehiculo,fecha,this.Descripcion.getText());
                us2.crear(usr);
                JOptionPane.showMessageDialog(null, "Mecánico solicitado con exito");
                this.dispose();
                menuPrincipal eng = new menuPrincipal();
                eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
                eng.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error: " + e,
                    "Hey!", JOptionPane.ERROR_MESSAGE);
            }   
        }
    }//GEN-LAST:event_BotonSolicitarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solicitarMecánico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solicitarMecánico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solicitarMecánico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solicitarMecánico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new solicitarMecánico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Anno;
    private javax.swing.JButton BotonSolicitar;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JComboBox<String> Dia;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JLabel Usuario;
    private javax.swing.JComboBox<String> Vehiculos;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables




}
