/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Controladores.UsuarioControlador;
import Controladores.ValletControlador;
import Controladores.parqueoControlador;
import Controladores.vehiculoControlador;
import Modelo.Parqueos;
import Modelo.Usuarios;
import Modelo.Valletpedidos;
import Modelo.Vehiculos;
import java.awt.Color;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Daniel
 */
public class solicitarValet extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public solicitarValet()
    {
        //cambiarBorde();
        this.setTitle("Log in");
        initComponents();
        
        jButton9.setOpaque(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setBorderPainted(false);
        
        SolicitarBoton.setBackground(Color.WHITE);
        SolicitarBoton.setBorderPainted(false);
        
        Vehiculo.setBackground(Color.WHITE);
        Tiempo.setBackground(Color.WHITE);
        Entrega.setBackground(Color.WHITE);
        
    }
    
    public void fondo(Icon fondo)
    {
        this.fondo.setIcon(fondo);
    }
    
    public void cargarVehiculos()
    {
        vehiculoControlador us =  new vehiculoControlador();
        List<Vehiculos> vehiculos = us.todosLosVehiculos();
        int controlador = 0;
        for(Vehiculos u: vehiculos)
        {
            if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
            {
                this.Vehiculo.addItem(u.getTipo()+"-"+u.getMarca());
            }
        }
    }
    
    public void usuario(String usuario)
    {
        this.Usuario.setText(usuario);
        this.Usuario.setVisible(false);
        System.out.print(this.Usuario.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Vehiculo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Tiempo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        SolicitarBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Entrega = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 700));
        setMinimumSize(new java.awt.Dimension(400, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitar Valet");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 70, 210, 38);

        Vehiculo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Vehiculo.setToolTipText("Combo para seleccionar un vehículo");
        getContentPane().add(Vehiculo);
        Vehiculo.setBounds(40, 190, 210, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lugar de entrega");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 240, 272, 31);

        Tiempo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Tiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lo más pronto", "En 15 minutos", "en 30 minutos" }));
        Tiempo.setToolTipText("Combo para seleccionar el tiempo de entrega");
        getContentPane().add(Tiempo);
        Tiempo.setBounds(40, 380, 210, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tiempo de entrega");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 340, 272, 31);

        SolicitarBoton.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SolicitarBoton.setText("Solicitar");
        SolicitarBoton.setToolTipText("solicita el vallet");
        SolicitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(SolicitarBoton);
        SolicitarBoton.setBounds(230, 600, 130, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehículo");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 150, 272, 31);

        Entrega.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Entrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada Norte", "Entrada Sur", "Entrada Este", "Edificio A", "Edifcio B", "Edificio C" }));
        Entrega.setToolTipText("Combo para seleccionar el lugar de la entrega");
        getContentPane().add(Entrega);
        Entrega.setBounds(40, 280, 210, 40);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 37)); // NOI18N
        jLabel4.setText("Ready Parking");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 0, 270, 50);

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/volver.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 10, 40, 30);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 110, 200, 10);

        Usuario.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("A");
        Usuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Usuario);
        Usuario.setBounds(20, 600, 160, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Imagenes/degradado header.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 700);

        getAccessibleContext().setAccessibleName("Log in");
        getAccessibleContext().setAccessibleDescription("Iniciar sesión en el sistema");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SolicitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarBotonActionPerformed
        int salir = JOptionPane.showConfirmDialog (null, "¿Solicitar Vallet?","Vallet",JOptionPane.YES_NO_OPTION);
        if(salir == 0)
        {
            
            String Vehiculo = this.Vehiculo.getSelectedItem().toString();
            String[] Spliteado = Vehiculo.split("-");      
            System.out.print(" VehiculoSplit: "+Spliteado[0] + "-" + Spliteado[1]+"\n");
            
            vehiculoControlador us =  new vehiculoControlador();
            List<Vehiculos> vehiculos = us.todosLosVehiculos();
            int idVehiculo =0;
            for(Vehiculos u: vehiculos)
            {
                if(u.getIdDuenno().toString().equals(this.Usuario.getText()))
                {
                   if(u.getTipo().equals(Spliteado[0]) && u.getMarca().equals(Spliteado[1]))
                       idVehiculo = u.getId();
                }
            }
            
            try
            {
                
                short lugar = (short)this.Entrega.getSelectedIndex();
                short tiempo = (short)this.Tiempo.getSelectedIndex();
                
                ValletControlador us2 =  new ValletControlador();
                Valletpedidos usr = new Valletpedidos(0,parseInt(this.Usuario.getText()),idVehiculo,lugar,tiempo);
                us2.crear(usr);
                JOptionPane.showMessageDialog(null, "Vallet solicitado con exito");
                this.dispose();
                menuPrincipal eng = new menuPrincipal();
                eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
                eng.setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error: " + e,
                    "Hey!", JOptionPane.ERROR_MESSAGE);
            }   
        }
    }//GEN-LAST:event_SolicitarBotonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        menuPrincipal eng = new menuPrincipal();
        eng.usuario(this.Usuario.getText());
        eng.fondo(this.fondo.getIcon());
        eng.setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solicitarValet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solicitarValet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solicitarValet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solicitarValet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new solicitarValet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Entrega;
    private javax.swing.JButton SolicitarBoton;
    private javax.swing.JComboBox<String> Tiempo;
    private javax.swing.JLabel Usuario;
    private javax.swing.JComboBox<String> Vehiculo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables




}
